---
- name: Update APT cache
  apt:
    update_cache: yes

- name: Install required packages (curl, gnupg, unzip)
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - gnupg
    - unzip

- name: Add Jenkins APT keyring
  shell: "curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | sudo tee /usr/share/keyrings/jenkins-keyring.asc"

- name: Add Jenkins APT repository
  shell: sudo sh -c 'echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'

- name: Install OpenJDK 11 JRE
  apt:
    name: openjdk-11-jre
    state: present

- name: Update APT cache after installing dependencies
  apt:
    update_cache: yes

- name: Install Jenkins
  apt:
    name: jenkins
    state: present

- name: Start Jenkins service
  service:
    name: jenkins
    state: started

- name: Retrieve Jenkins initial admin password
  shell: cat /var/lib/jenkins/secrets/initialAdminPassword
  register: jenkins_password

- name: Print Jenkins initial admin password
  debug:
    msg: "Jenkins initial admin password is {{ jenkins_password.stdout }}"
